model:
  type: "gemini" #"ollama" ##
  name: "gemini-2.0-flash" #"llama3.1:8b" # ##
  #url: "http://13.203.148.228:11434/v1"

interview:
  duration_minutes: 45

tts:
  voice: "Kajal"
  language: "en-IN"
